"""renaming the address co,umn to location

Revision ID: 573aaf0ed283
Revises: e4e90294ed5a
Create Date: 2024-10-03 10:14:00.200229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573aaf0ed283'
down_revision = 'e4e90294ed5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('adress')
        op.alter_column('departments', 'adress', new_column_name= 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('location')

        op.alter_column('department', 'location', new_column_name = 'adress')
    # ### end Alembic commands ###
